version: "3.9"
services:
  node-app:
    container_name: node-app
    profiles: 
      - dev
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
    environment:
      - NODE_ENV=development
    env_file:
      - .env.dev
    networks:
      - app-network
    command: ["yarn", "dev"]

  node-app-prod:
    container_name: node-app-prod
    profiles: 
      - prod
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
    environment:
      - NODE_ENV=production
    env_file:
      - .env.prod
    networks:
      - app-network
    command: ["yarn", "start"]

  react-app:
    container_name: react-app
    profiles: 
      - dev
    build:
      context: react
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./react:/usr/src/app"
    environment:
      - NODE_ENV=development
      - PORT=8080
    networks:
      - app-network
    command: ["yarn", "start"]

  react-app-prod:
    container_name: react-app-prod
    profiles: 
      - prod
    build:
      context: react
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./react:/usr/src/app"
    environment:
      - NODE_ENV=production
      - PORT=8080
    networks:
      - app-network
    command: ["yarn", "start"]

  mysql:
    container_name: mysql
    profiles: 
      - dev
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    ports:
      - "3306:3306"
    volumes:
      - dbdata-dev:/var/lib/mysql
      - ./db/ddl:/docker-entrypoint-initdb.d
      - ./db/seed_dev:/docker-entrypoint-initdb.d/seed_files
    networks:
      - app-network

  mysql-prod:
    container_name: mysql-prod
    profiles: 
      - prod
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    ports:
      - "3306:3306"
    volumes:
      - dbdata-prod:/var/lib/mysql
      - ./db/ddl:/docker-entrypoint-initdb.d
      - ./db/seed_prod:/docker-entrypoint-initdb.d/seed_files
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  dbdata-dev:
  dbdata-prod: