version: "3.9"
services:
  node-app:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    command: ["yarn", "dev"]

  react-app:
    build:
      context: react
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./react:/usr/src/app"
    environment:
      - NODE_ENV=development
      - PORT=8080
    networks:
      - app-network
    command: ["yarn", "start"]

  mysql:
    container_name: mysql
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/ddl:/docker-entrypoint-initdb.d
    networks:
      - app-network



networks:
  app-network:
    driver: bridge

volumes:
  dbdata: